<?php

return [
    'bios.andres.position' => 'Presidente/Co-fondatore',
    'bios.andres.text' => '<p>Ho 18 anni (quasi 19) e sono nato in Canada, ma i miei genitori sono entrambi colombiani. Ho vissuto per lo più a Mississauga e Toronto prima di trasferirsi a Milano per studiare.Ho iniziato presso l\'Università Bocconi lo scorso settembre e attualmente mi voglio laureare in Finanza nell\'ambito del programma di Economia e Finanza Internazionale. Anche se, in questo momento, Zugy è il mio obiettivo, aspiro ad intraprendere una carriera nel settore dei servizi finanziari.</p>',
    'bios.galen.position' => 'Responsabile della Tecnologia',
    'bios.galen.text' => '<p>Attualmente sono al secondo anno di studio di Computer Science presso la UCL di Londra. Ho una vasta esperienza nello sviluppo web stack completo e mi entusiasma poter garantire che Zugy utilizzi la più recente tecnologia per offrire ai propri clienti il miglior servizio ed esperienza possibile.</p>',
    'bios.matthias.position' => 'Responsabile Finanziario',
    'bios.matthias.text' => '<p>Vengo da Colonia, in Germania, e attualmente studio Economia presso l\'Università Bocconi di Milano. E’ dal mese di giugno 2015 che stiamo lavorando su Zugy insieme con i miei amici e partner Rafael, Andres, Victor e Leonie. Ho deciso di prendere la posizione di responsabile finanziario nella nostra azienda. Sono sempre stato appassionato di contabilità e, in passato, ho lavorato, nel settore della contabilità, per un progetto scolastico no-profit nel nord dell\'India.  Penso che siamo una squadra solida e non vedo l\'ora di lavorare insieme con gli altri per i prossimi anni su Zugy.</p>',
    'bios.motyat.position' => 'Responsabile del Marketing',
    'bios.motyat.text' => 'Sono una diciannovenne americana attualmente al mio secondo anno di studi presso l\'Università Bocconi. Mentre la mia laurea in corso è incentrata ampiamente su temi di Economia e Management, i miei interessi personali si rivolgono all\'area vendite e marketing. Ho maturato esperienza nella gestione di marchi online e ho lavorato con delle aziende per colmare il divario tra loro ei loro clienti. Il mio obiettivo è quello di rendere Zugy un nome familiare a Milano e rendere visibile in tutto il mondo il marchio Zugy.
 ',
    'bios.rafael.position' => 'Amministratore delegato/ Co-fondatore',
    'bios.rafael.text' => '<p>Ho 19 anni e sono portoghese. Per tutta la mia vita ho sempre aspirato ad essere uno studente in una importante università di economia all’estero. Per raggiungere questo obiettivo mi sono iscritto a una scuola internazionale, al fine di imparare una varietà di lingue come il francese e lo spagnolo, ma soprattutto l’inglese. Oggi frequento l\'Università Bocconi per conseguire il mio diploma di laurea in Economia e gestione.</p>
<p>Da quando mi ricordo ho sempre cercato di analizzare le situazioni e avere idee su come fare meglio. Zugy diventerà la mia nuova ambizione e cosi rivoluzionare il settore delle bevande alcoliche.</p>',
    'bios.victor.position' => 'Direttore Operativo',
    'bios.victor.text' => '<p>Io sono il più vecchio membro della Zugy. Infatti, ho conseguito una laurea in economia aziendale nel 1993 presso l\'Università di Sabana Colombia. Dopo questo, la mia prima esperienza di lavoro è stata nel dipartimento delle risorse umane di una banca colombiana. Nel 1996, sono stato responsabile di una società di logistica internazionale. Nel 2002, sono diventato il capo della amministrazione a Sismopetrol della Colombia per il reparto di esplorazione nella ricerca di idrocarburi. Nel 2007, mi sono trasferito in Italia e mi sono laureato in economia presso l\'Università degli Studi di Milano-Bicocca nel 2010. Infine, ho seguito il corso di "Somministrazione Alimenti e Bevande" (SAB) e ho conseguito la relativa licenza necessaria affinché il progetto Zugy possa concretizzarsi. Sto anche gestendo un ristorante di cucina caraibica a Milano con mio fratello.</p>',
];