<?php

return [
    'bios.andres.position' => 'Presidente/Fondatore',
    'bios.andres.text' => '<p>Sono nato in Canada dopo che i miei genitori si sono trasferiti dalla Colombia e sono cresciuto a Mississauga prima di spostarmi a Milano per studiare. Decisi di fare richiesta d\'ammissione in università estere perché volevo espandere i miei orizzonti in termini di prospettive lavorative e perché volevo sperimentare una cultura diversa. Ho cominciato a frequentare l\'Università bocconi nel settembre del 2014 e ho scelto un major in finanza. Spero di riuscire a trasferirmi a Management, economia pura o informatica.</p>
<p>Voglio che Zugy diventi la soluzione sostenibile per i consumatori del ventunesimo secolo e che continui a sviluppare nuovi metodi per soddisfare i suoi clienti.</p>',
    'bios.galen.position' => 'Responsabile della Tecnologia',
    'bios.galen.text' => '<p>Attualmente sono al secondo anno di studio di Computer Science presso la UCL di Londra. Ho una vasta esperienza nello sviluppo web stack completo e mi entusiasma poter garantire che Zugy utilizzi la più recente tecnologia per offrire ai propri clienti il miglior servizio ed esperienza possibile.</p>',
    'bios.matthias.position' => 'Capo d\'amministrazione',
    'bios.matthias.text' => '<p>Vengo da Colonia, in Germania, e attualmente studio Economia presso l\'Università Bocconi di Milano. E’ dal mese di giugno 2015 che stiamo lavorando su Zugy insieme con i miei amici e partner Andres, Victor e Leonie. Ho deciso di prendere la posizione di responsabile finanziario nella nostra azienda. Sono sempre stato appassionato di contabilità e, in passato, ho lavorato, nel settore della contabilità, per un progetto scolastico no-profit nel nord dell\'India.  Penso che siamo una squadra solida e non vedo l\'ora di lavorare insieme con gli altri per i prossimi anni su Zugy.</p>',
    'bios.victor.position' => 'Direttore Operativo',
    'bios.victor.text' => '<p>Io sono il più vecchio membro della Zugy. Infatti, ho conseguito una laurea in economia aziendale nel 1993 presso l\'Università di Sabana Colombia. Dopo questo, la mia prima esperienza di lavoro è stata nel dipartimento delle risorse umane di una banca colombiana. Nel 1996, sono stato responsabile di una società di logistica internazionale. Nel 2002, sono diventato il capo della amministrazione a Sismopetrol della Colombia per il reparto di esplorazione nella ricerca di idrocarburi. Nel 2007, mi sono trasferito in Italia e mi sono laureato in economia presso l\'Università degli Studi di Milano-Bicocca nel 2010. Infine, ho seguito il corso di "Somministrazione Alimenti e Bevande" (SAB) e ho conseguito la relativa licenza necessaria affinché il progetto Zugy possa concretizzarsi. Sto anche gestendo un ristorante di cucina caraibica a Milano con mio fratello.</p>',
];
