@section('title', 'Terms and Conditions')
@section('meta_description', 'Terms and Conditions for ' . config('site.name'))

@extends('layouts.default')

@section('content')
    <div class="page-header">
        <h1>Zugy Services S.r.l. Terms and Conditions </h1>
    </div>
    <p><b>Please read these conditions carefully before using Zugy Services S.r.l website. By using Services, you signify your agreement to be bound by these conditions.
            When you use Zugy Services S.r.l services (for example Your Profile), you will also be subject to the terms, guidelines and conditions applicable to that Zugy Services S.r.l Service ("Service Terms"). If these Conditions of Use are inconsistent with the Service Terms, those Service Terms will control.</b></p>
    <h2>1. PRIVACY</h2>
    <p>Please review our <a href="{!! localize_url('routes.privacy-policy') !!}">Privacy Policy</a>, which also govern your use of Zugy Services S.r.l Services, to understand our practices.</p>
    <h2>2. ELECTRONIC COMMUNICATIONS</h2>
    <p>When you use any or send e-mails, text messages, and other communications from your desktop or mobile device to us, you are communicating with us electronically. We will communicate with you electronically in a variety of ways, such as by e-mail, push notices or by posting e-mail messages or communications on the website or through the other Zugy Services S.r.l Services. For contractual purposes, you consent to receive communications from us electronically and you agree that all agreements, notices, disclosures and other communications that we provide you electronically satisfy any legal requirement that such communications be in writing, unless mandatory applicable laws specifically require a different form of communication.</p>
    <h2>3. COPYRIGHT, AUTHORS' RIGHTS AND DATABASE RIGHTS</h2>
    <p>All content included in or made available through our Zugy Services, such as text, graphics, logos, button icons, images, audio clips, digital downloads and data compilations is the property of Zugy Services S.r.l. The compilation of all content included in or made available through any Zugy Services is the exclusive property of Zugy Services and is protected by international copyright and database right laws.</p>
    <p>You may not extract and/or re-utilise parts of the content of any Zugy Services without our express written consent. In particular, you may not utilise any data mining, robots, or similar data gathering and extraction tools to extract (whether once or many times) for re-utilisation any substantial parts of the content of any Zugy Services, without our express written consent. You may also not create and/or publish your own database that features substantial parts of any Zugy Services (e.g. our prices and product listings) without our express written consent.</p>
    <h2>4. LICENCE AND ACCESS</h2>
    <p>Subject to your compliance with these Conditions of Use and applicable Service Terms and your payment of any applicable fees, Zugy Services or its content providers grant you a limited, non-exclusive, non-transferable, non-sub licensable licence to access and make personal and non-commercial use of the Zugy Services. This licence does not include any resale or commercial use of any Zugy Services or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of any Zugy Services or its contents; any downloading or copying of account information for the benefit of another merchant; or any use of data mining, robots, or similar data gathering and extraction tools.</p>
    <p>All rights not expressly granted to you in these Conditions of Use or any Service Terms are reserved and retained by Zugy or its licensors, suppliers, publishers, rights holders, or other content providers. No Zugy Services, nor any part of any Zugy Services, may be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without our express written consent. You may not frame or use framing techniques to enclose any trademark, logo or other proprietary information (including images, text, page layout, or form) of Amazon without our express written consent. You may not use any Meta tags or any other "hidden text" utilising Zugy's names or trademarks without our express written consent.</p>
    <p>You may not misuse the Zugy Services. You may use the Zugy Services only as permitted by law. The licences granted by Zugy terminate if you do not comply with these Conditions of Use or any Service Terms.</p>
    <h2>5. YOUR ACCOUNT</h2>
    <p>If you use any Zugy Services you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer and devices, and to the extent permitted by applicable law you agree to accept responsibility for all activities that occur under your account or password. You should take all necessary steps to ensure that the password is kept confidential and secure and should inform us immediately if you have any reason to believe that your password has become known to anyone else, or if the password is being, or is likely to be used in an unauthorised manner. You are responsible for ensuring that the details you provide us with are correct and complete, and for informing us of any changes to the information you have provided. You can access and update much of the information you have provided us with, including your account settings, in Your Account area of the website.</p>
    <p>You must not use any Zugy Services: (I) in any way that causes, or is likely to cause, any Zugy Services, or any access to it to be interrupted, damaged or impaired in any way, or (ii) for fraudulent purposes, or in connection with a criminal offence or other unlawful activity, or (iii) to cause annoyance, inconvenience or anxiety.</p>
    <p>We reserve the right to refuse service, terminate accounts or remove or edit content if you are in breach of applicable laws, these Conditions of Use or any other applicable terms and conditions, guidelines or policies.</p>
    <h2>6. REVIEWS, COMMENTS, COMMUNICATIONS AND OTHER CONTENT</h2>
    <p>Visitors may post reviews, comments and other content; send e-cards and other communications; and submit suggestions, ideas, comments, questions or other information, as long as the content is not illegal, obscene, abusive, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any form of "spam". You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin of a card or other content. We reserve the right, the obligation to remove or edit such content. If you believe that any content on or advertised for sale on any Zugy Services contains a defamatory statement, or that your intellectual property rights are being infringed by an item or information on any Zugy Services, please notify us by completing and submitting the appropriate If you post content or submit material, and unless we indicate otherwise, you grant: (a) Zugy a non-exclusive, royalty-free and fully sub licensable and transferable rights to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media; and (b) Zugy, its sublicense’s and transferees the right to use the name that you submit in connection with such content, if they choose. No moral rights are assigned under this provision.</p>
    <p>You agree that the rights you grant above are irrevocable during the entire period of protection of your intellectual property rights associated with such content and material. To the extent permitted by law, you agree to waive your right to be identified as the author of such content and your right to object to derogatory treatment of such content. You agree to perform all further acts necessary to perfect any of the above rights granted by you to Zugy including the execution of deeds and documents, at our request.</p>
    <p>You represent and warrant that you own or otherwise control all of the rights to the content that you post; that, as at the date that the content or material is posted: (I) the content and material is accurate; and (ii) use of the content and material you supply does not breach any applicable policies or guidelines and will not cause injury to any person or entity (including that the content or material is not defamatory). You agree to indemnify Zugy for all claims brought by a third party against Zugy arising out of or in connection with the content and material you supply except to the extent that any liability arises from our failure to properly remove the content when it is notified of the illegal nature of the content (Notice Form) arising out of or on the grounds of, or originating from the content that you have communicated to us.</p>
    <h2>7. INTELLECTUAL PROPERTY CLAIMS</h2>
    <p>Zugy respects the intellectual property of others. If you believe that your intellectual property rights have been used in a way that gives rise to concerns of infringement, please contact us at {!! config('site.email.support') !!} immediately.</p>.
    <h2>8. ZUGY SOFTWARE TERMS</h2>
    <p>In addition to these Terms and Conditions, the terms found apply to any software (including any updates or upgrades to the software and any related documentation) that we make available to you from time to time for your use in connection with Zugy Services (the "Zugy Software").</p>
    <h2>9. OUR LIABILITY</h2>
    <p>We will do our utmost to ensure that availability of the Zugy Services will be uninterrupted and that transmissions will be error-free. However, due to the nature of the internet, this cannot be guaranteed. Also, your access to Zugy Services may also be occasionally suspended or restricted to allow for repairs, maintenance, or the introduction of new facilities or services. We will attempt to limit the frequency and duration of any such suspension or restriction.</p>
    <p>Zugy will not be responsible for (i) losses that were not caused by any breach on our part, or (ii) any business loss (including loss of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure), or (iii) any indirect or consequential losses that were not foreseeable to both you and us when you commenced using the Zugy Services.</p>
    <p>We will not be held responsible for any delay or failure to comply with our obligations under these conditions if the delay or failure arises from any cause which is beyond our reasonable control. This condition does not affect your legal right to have goods sent or services provided within a reasonable time or to receive a refund if goods or services ordered cannot be supplied within a reasonable time owing to a cause beyond our reasonable control.
        The laws of some countries do not allow some or all of the limitations described above. If these laws apply to you, some or all of the above limitations may not apply to you and you might have additional rights.</p>
    <p>Nothing in these conditions limits or excludes our responsibility for fraudulent representations made by us or for death or personal injury caused by our negligence or wilful misconduct.</p>
    <h2>10. ALTERATIONS TO SERVICE OR AMENDMENTS TO THE CONDITIONS OF USE</h2>
    <p>We reserve the right to make changes to any Zugy Services, policies, terms and conditions including these Conditions of Use, and Service Terms at any time. You will be subject to the terms and conditions, policies and Conditions of Use in force at the time that you use the Zugy Services. If any of these Conditions of Use is deemed invalid, void, or for any reason unenforceable, that condition will be deemed severable and will not affect the validity and enforceability of any remaining condition.</p>
    <h2>11. WAIVER</h2>
    <p>If you breach these Conditions of Use and we take no action, we will still be entitled to use our rights and remedies in any other situation where you breach these Conditions of Use.</p>
    <h2>12. MINORS</h2>
    <p>We do not sell products for purchase by minors. Only allow purchase by adults. If you are under 18 you may not use the Zugy Services only with the involvement of a parent or guardian. It is forbidden to buy alcohol under 18 years of age in Italy.</p>
@endsection