@section('title', 'Termini e condizioni')
@section('meta_description', 'Termini e condizioni - ' . config('site.name'))

@extends('layouts.default')

@section('content')
    <div class="page-header">
        <h1>Zugy Servizi S.r.l. Termini e condizioni</h1>
    </div>
    <p><b>Si prega di leggere attentamente queste condizioni prima di utilizzare il sito Zugy Servizi S.r.l. Utilizzando i servizi, l'utente accetta di essere vincolato da queste condizioni. Quando si utilizza Zugy Servizi Servizi S.R.L (per esempio il tuo profilo), sarà anche essere soggetti ai termini, alle linee guida e le condizioni vigenti per tale Zugy Servizi S.r.l servizio ( "Servizio Termini"). Se queste condizioni di utilizzo sono incompatibile con i termini di servizio, i Termini di servizio si controllano.</b></p>
    <h2>1. PRIVACY</h2>
    <p>Si prega di rivedere la nostra <a href="{!! localize_url('routes.privacy-policy') !!}">Privacy Policy</a>, che disciplina anche l'utilizzo di Zugy Servizi S.R.L Servizi, per capire le nostre pratiche.</p>
    <h2>2. COMUNICAZIONI VIA COMPUTER</h2>
    <p>Quando si utilizza qualunque o inviare e-mail, messaggi di testo e altre comunicazioni dal desktop o dispositivo mobile per noi, si comunica con noi elettronicamente. Comunicheremo con voi elettronicamente in una varietà di modi, ad esempio tramite e-mail, le comunicazioni di spinta o di inviare messaggi di posta elettronica o comunicazioni sul sito web o attraverso le altre Zugy Servizi S.R.L Servizi. Ai fini contrattuali, l'utente acconsente a ricevere comunicazioni da noi elettronicamente e si accetta che tutti gli accordi, gli avvisi, informazioni e altre comunicazioni che vi forniremo elettronicamente soddisfino i requisiti legali che tali comunicazioni in forma scritta, a meno che leggi vigenti specificamente richiedono una forma diversa di comunicazione.</p>
    <h2>3. COPYRIGHT, DIRITTI DI AUTORE E DI DATABASE</h2>
    <p>Tutti i contenuti inclusi o resi disponibili attraverso il nostro Zugy servizi, come ad esempio testo, grafica, loghi, icone, immagini, clip audio, download digitali e compilazioni di dati è di proprietà di Zugy Servizi S.r.l. La compilazione di tutti i contenuti inclusi o resi disponibili attraverso qualsiasi connessione Zugy è di proprietà esclusiva di Zugy servizi ed è protetto da copyright e database leggi internazionali destra.</p>
    <p>Non si può estrarre e / o riutilizzare parti del contenuto dei Servizi Zugy senza il nostro esplicito consenso scritto. In particolare, non si può utilizzare qualsiasi data mining, robot o altri sistemi di raccolta dei dati e di estrazione strumenti per estrarre (se una o più volte) per il reimpiego di parti sostanziali del contenuto di qualsiasi servizi Zugy, senza il nostro esplicito consenso scritto. Si può anche non creare e / o pubblicare il proprio database che dispone di una parte sostanziale di qualsiasi Servizio Zugy (ad esempio i nostri prezzi e annunci di prodotto) senza il nostro esplicito consenso scritto.</p>

    <h2>4. LICENZA ED ACCESSO</h2>
    <p>Fatto salvo il vostro rispetto di queste Condizioni d'Uso e applicabile Termini di servizio e il pagamento di tutte le tasse applicabili, Zugy Servizi o dei suoi fornitori di contenuti si concede una licenza non esclusiva, non trasferibile, licenza licenziabile non sub limitata per accedere e fare personali e l'uso non commerciale dei servizi Zugy. Questa licenza non include la rivendita o l'uso commerciale dei Servizi Zugy o il suo contenuto; la raccolta e l'uso di elenchi, descrizioni o prezzi; qualsiasi uso derivativo dei Servizi Zugy o il suo contenuto; qualsiasi scaricamento o la duplicazione delle informazioni cliente a vantaggio di un altro commerciante; o qualsiasi utilizzo di data mining, robot o simili strumenti di raccolta dei dati e di estrazione.</p>
    <p>Tutti i diritti non espressamente concessi a voi in queste Condizioni di utilizzo o di qualsiasi Termini di servizio sono riservati e mantenuti da Zugy o dei suoi licenziatari, fornitori, gli editori, i titolari dei diritti, o di altri fornitori di contenuti. No Zugy Servizi, né alcuna parte di qualsiasi servizi Zugy, può essere riprodotto, duplicato, copiato, venduto, rivenduto, visitato, o in altro modo sfruttati per scopi commerciali senza il nostro esplicito consenso scritto. L'utente non può frame o utilizzare tecniche di framing per racchiudere qualsiasi marchio, logo o altre informazioni proprietarie (comprese immagini, testi, layout di pagina, o forma) di Amazon senza il nostro esplicito consenso scritto. E 'vietato utilizzare meta tag o altro "testo nascosto" che i nomi o marchi di Zugy senza il nostro esplicito consenso scritto.</p>
    <p>L'utente non può abusare dei Servizi Zugy. È possibile utilizzare i Servizi Zugy solo come consentito dalla legge. Le licenze concesse da Zugy terminano se non si attenga alle presenti Condizioni d'uso o di qualsiasi Termini di servizio.</p>

    <h2>5. Il TUO ACCOUNT</h2>
    <p>Se si utilizza qualsiasi Servizi Zugy sei responsabile del mantenimento della riservatezza del proprio account e password e di limitare l'accesso al computer e dispositivi, e nella misura consentita dalla legge applicabile l'utente accetta di assumersi la responsabilità di tutte le attività che avvengono sul suo account o parola d'ordine. Si dovrebbe prendere tutte le misure necessarie per garantire che la password è riservatezza e la sicurezza e dovrebbe informarci immediatamente se si ha motivo di credere che la password è diventato noto a chiunque altro, o se la password è l'essere, o è probabile che sia utilizzato in modo non autorizzato. L'utente è responsabile di assicurare che i dati che ci forniscono sono corrette e complete, e per averci informato di eventuali modifiche alle informazioni che ci avete fornito. È possibile accedere e aggiornare gran parte delle informazioni che ci avete fornito con, tra le impostazioni dell'account, nella propria area account del sito.</p>
    <p>Non si deve utilizzare Servizi Zugy: (I) in alcun modo che provoca, o rischia di provocare, qualsiasi Zugy Servizi, o l'accesso ad esso per essere interrotti, danneggiato o alterato in alcun modo, o (ii) per scopi fraudolenti , o in connessione con un reato o altre attività illegali, o (iii) per causare disturbo, disagio o ansia.</p>
    <p>Ci riserviamo il diritto di rifiutare il servizio, chiudere i conti o rimuovere o modificare il contenuto, se si è in violazione delle leggi in vigore, le presenti Condizioni di Utilizzo o qualsiasi altro termine e le condizioni applicabili, linee guida o politiche.</p>

    <h2>6. REVIEWS, COMMENTI, COMUNICAZIONI ED ALTRO TIPO DI CONTENUTO</h2>
    <p>I visitatori possono pubblicare recensioni, commenti e altri contenuti; inviare e-cards e altre comunicazioni; e inviare suggerimenti, idee, commenti, domande o altre informazioni, a condizione che il contenuto non è illegale, osceno, abusivo, minaccioso, diffamatorio, lesivo della privacy, violazione dei diritti di proprietà intellettuale, o comunque dannoso per terzi o discutibile e fa non contengono o consistono di virus software, campagne politiche, promozioni commerciali, catene di Sant'Antonio, mailing di massa o qualsiasi forma di "spam". L'utente non può utilizzare un indirizzo e-mail falso, impersonare altre persone o entità, o altrimenti nascondere l'origine di una carta o altri contenuti. Ci riserviamo il diritto, l'obbligo di rimuovere o modificare tali contenuti. Se credi che qualsiasi contenuto o pubblicizzati in vendita su tutti i servizi Zugy contiene una dichiarazione diffamatoria, o che i diritti di proprietà intellettuale sono stati violati da un elemento o informazioni su tutti i servizi Zugy, si prega di avvisare compilando e presentando l'appropriato Se si pubblicare contenuti o inviare materiale, e se non diversamente indicato, si concede: (a) Zugy una licenza non esclusiva, e pienamente sub licenziabile e diritti trasferibili di utilizzare, riprodurre, modificare, adattare, pubblicare, tradurre, creare lavori derivati ​​royalty-free da, distribuire e visualizzare tali contenuti in tutto il mondo con qualsiasi mezzo; e (b) Zugy, i suoi sub-licenza di cessionari e il diritto di utilizzare il nome che si presenta in relazione a tali contenuti, se scelgono. Nessun diritto morali vengono assegnati ai sensi della presente disposizione.</p>
    <p>L'utente accetta che i diritti si concede sopra sono irrevocabili durante tutto il periodo di protezione dei diritti di proprietà intellettuale associati a tali contenuti e materiale. Nella misura consentita dalla legge, l'utente accetta di rinunciare il vostro diritto di essere identificato come l'autore di tali contenuti e il diritto di opporsi al trattamento dispregiativo di tali contenuti. L'utente accetta di eseguire tutte le ulteriori atti necessari per perfezionare alcuno dei diritti di cui sopra concesse da voi per Zugy tra cui l'esecuzione di atti e documenti, su nostra richiesta.</p>
    <p>L'utente dichiara e garantisce di possedere o altrimenti controllare tutti i diritti per il contenuto che si posta; che, alla data che il contenuto o il materiale è pubblicato: (I) il contenuto e il materiale è accurata; e (ii) l'uso del contenuto e del materiale fornito non violare eventuali politiche o linee guida applicabili e non causerà danni a qualsiasi persona o entità (compreso che il contenuto o il materiale non è diffamatori). L'utente accetta di indennizzare Zugy per tutte le pretese avanzate da terzi contro Zugy derivanti da o in connessione con il contenuto ed il materiale si fornisce se non nella misura in cui la responsabilità deriva dalla nostra incapacità di rimuovere correttamente il contenuto quando viene notificata la la natura illegale del contenuto (Modulo di Avviso) derivante da o per motivi di, o provenienti dal contenuto che si è comunicato a noi.</p>

    <h2>7. PROTEZIONE DELLA PROPRIETA´ INTELLETTUALE</h2>
    <p>Zugy rispetta la proprietà intellettuale di altri. Se ritenete che i vostri diritti di proprietà intellettuale sono stati utilizzati in un modo che dà luogo a preoccupazioni di infrazione, contattaci all'indirizzo {!! config('site.email.support') !!} immediatamente.</p>

    <h2>8. ZUGY TERMINI DI UTILIZZO DEL SOFTWARE</h2>
    <p>In aggiunta a questi termini e condizioni, i termini trovati applica a qualsiasi software (inclusi eventuali aggiornamenti o aggiornamenti al software e la documentazione inviata) che mettono a disposizione di volta in volta per l'uso in connessione con Zugy servizi (il " Zugy Software ").</p>

    <h2>9. RESPONSABILITA` LEGALE</h2>
    <p>Faremo del nostro meglio per garantire che la disponibilità del Zugy servizi sarà ininterrotto e che le trasmissioni sarà privo di errori. Tuttavia, a causa della natura di Internet, questo non può essere garantita. Inoltre, l'accesso a servizi Zugy può anche essere occasionalmente sospeso o limitato per consentire la riparazione, la manutenzione o l'introduzione di nuove strutture o servizi. Cercheremo di limitare la frequenza e la durata di tale sospensione o la limitazione.</p>
    <p>Zugy non sarà responsabile per (i) le perdite che non sono stati causati da una violazione da parte nostra, o (ii) qualsiasi perdita di business (inclusa la perdita di profitti, ricavi, contratti, risparmi previsti, i dati, avviamento o spese inutili), o (iii) eventuali perdite indirette o consequenziali, che non erano prevedibili per voi e per noi quando si è iniziata l'utilizzo dei Servizi Zugy.</p>
    <p>Non saremo ritenuti responsabili per qualsiasi ritardo o il mancato rispetto dei nostri obblighi in queste condizioni se il ritardo o guasto si verifica per qualsiasi causa, che è al di là del nostro controllo. Questa condizione non influisce sul diritto legale di avere merce inviata o servizi forniti entro un tempo ragionevole o per ricevere un rimborso se beni o servizi ordinati non possono essere forniti entro un termine ragionevole a causa di una causa al di fuori del nostro controllo. Le leggi di alcuni paesi non consentono alcune o tutte le limitazioni sopra descritte. Se queste leggi si applicano a voi, alcune o tutte le limitazioni di cui sopra potrebbero non essere applicabili a voi e si potrebbe avere ulteriori diritti.</p>
    <p>Niente in questi limiti condizioni o esclude la nostra responsabilità per le rappresentazioni fraudolente fatte da noi o per morte o lesioni personali causate da nostra negligenza o dolo.</p>

    <h2>10. CAMBIAMENTI NEL SERVIZIO O MODIFICHE DELLE CONDIZIONI DI UTILIZZO</h2>
    <p>Ci riserviamo il diritto di apportare modifiche a qualsiasi Zugy servizi, politiche, termini e condizioni, tra cui queste Condizioni d'uso e di servizio Termini in qualsiasi momento. Lei sarà soggetto ai termini e condizioni, politiche e condizioni di utilizzo vigenti al momento in cui si utilizzano i servizi Zugy. Se una di queste Condizioni d'uso è considerata non valida, nulla o per qualsiasi motivo inapplicabile, tale condizione sarà considerata separabile e non pregiudicherà la validità e l'applicabilità delle altre condizioni.</p>

    <h2>11. DISCLAIMER</h2>
    <p>In caso di violazione delle presenti Condizioni d'Uso e non ci assumiamo alcuna azione, ci sarà ancora il diritto di utilizzare i nostri diritti e rimedi in qualsiasi altra situazione in cui di violazione di queste Condizioni d'Uso.</p>

    <h2>12. MINORI</h2>
    <p>Non vediamo bevande alcoliche ai minori. È consentita la vendita solo ad adulti sopra i diciotto anni di età. Se hai mano di diciotto anni è necessario il coinvolgimento di un genitore responsabile o di un tutore  legalmente riconosciuto.</p>
@endsection