<?php

return [
    'bios.andres.position' => 'President/Co-Founder',
    'bios.andres.text' => '<p>I am 18 years old (almost 19) and was born in Canada but my parents are both Colombian. I lived mostly in Mississauga and Toronto before moving to Milan for school. I started at Università Bocconi last September and am currently majoring in Finance within the International Economics and Finance program. Although Zugy is my focus at the moment I also aspire for a career in the financial services industry.</p>',
    'bios.galen.position' => 'Chief Technology Officer',
    'bios.galen.text' => '<p>I am currently in my second year studying Computer Science at UCL in London. I have wide experience in full stack web development and am passionate in ensuring that Zugy is using the newest technology to bring its customers the best service and user experience possible.</p>',
    'bios.matthias.position' => 'Chief Financial Officer',
    'bios.matthias.text' => '<p>I\'m from Cologne, Germany and I currently study Economics at Bocconi University in Milan. We have been working together on Zugy since June 2015, with my friends and partners Rafael, Andres, Victor and Leonie. I decided to take the position as CFO in our company, since I was always a passionate about accounting and work in accounting at a non-profit school project in the North of India. Together I think we are a solid team and I am looking forward to the future years we will work together on Zugy!</p>',
    'bios.rafael.position' => 'CEO/Co-Founder',
    'bios.rafael.text' => '<p>I am 19 years old and Portuguese. Throughout my whole student life I always aspired to major in economics on a university abroad. To reach this I moved to an international school in order to learn a variety of languages (French, Spanish) but mainly to be fluent in English. Today I am at Bocconi University in pursuit of my diploma in economics and management.</p>
        <p>Ever since I can remember I\'ve always tried to analyze a situation and have ideas of how to make them better. Zugy will become my new ambition and revolutionize the alcohol industry.</p>',
    'bios.victor.position' => 'Chief Operating Officer',
    'bios.victor.text' => '<p>I am the oldest member of Zugy. In fact, I obtained a degree in business administration in 1993 from the Sabana University of Colombia. After this, my first work experience was in the human resource department of a Colombian bank. In 1996, I was responsible for an international logistics company. In 2002, I became the head of administration at Sismopetrol of Colombia for the department of exploration. In 2007, I moved to Italy and graduated in economics at the University of Milan-Bicocca in 2010. I\'m currently taking the course "somministrazione alimenti e bevande" (SAB) required for the development of Zugy (the license). I also manage a restaurant in Milan with my brother.</p>',
];